### ISSUE TITLE
求告知keras和tensorflow的版本

### ISSUE THREAD

**Issue by superguopeng** [liuhuanyong/MedicalNamedEntityRecognition#7]

**Comment by HJW3536** [comment]
有知道keras和tensorflow版本的吗？

**Comment by 18813055625** [comment]
同问

**Comment by 18813055625** [comment]
keras=2.2.0  tensorflow=1.14.0  能运行

**Comment by HJW3536** [comment]
> keras=2.2.0 tensorflow=1.14.0 能运行

你好  你我晚上试了下 确实能运行。但是还有些其他问题想和你请教一下，能留个邮箱吗？

**Comment by 18813055625** [comment]
直接在这上面说吧

**Comment by HJW3536** [comment]
训练完成之后输出是：
Traceback (most recent call last):
  File "lstm_train.py", line 161, in <module>
    ner.train_model()
  File "lstm_train.py", line 130, in train_model
    self.draw_train(history)
  File "lstm_train.py", line 137, in draw_train
    plt.plot(history.history['acc'])
KeyError: 'acc
这是什么意思

**Comment by jiajiaholiday** [comment]
> 训练完成之后输出是：
> Traceback (most recent call last):
> File "lstm_train.py", line 161, in
> ner.train_model()
> File "lstm_train.py", line 130, in train_model
> self.draw_train(history)
> File "lstm_train.py", line 137, in draw_train
> plt.plot(history.history['acc'])
> KeyError: 'acc
> 这是什么意思

你好，我也遇到了这个问题，请问你解决了吗？

**Comment by HJW3536** [comment]
> 训练完成之后输出是：
> Traceback (most recent call last):
> File "lstm_train.py", line 161, in
> ner.train_model()
> File "lstm_train.py", line 130, in train_model
> self.draw_train(history)
> File "lstm_train.py", line 137, in draw_train
> plt.plot(history.history['acc'])
> KeyError: 'acc
> 这是什么意思
> 
> 你好，我也遇到了这个问题，请问你解决了吗？

没有。还在学习中。

**Comment by suborigin** [comment]
> > 训练完成之后输出是：
> > Traceback (most recent call last):
> > File "lstm_train.py", line 161, in
> > ner.train_model()
> > File "lstm_train.py", line 130, in train_model
> > self.draw_train(history)
> > File "lstm_train.py", line 137, in draw_train
> > plt.plot(history.history['acc'])
> > KeyError: 'acc
> > 这是什么意思
> 
> 你好，我也遇到了这个问题，请问你解决了吗？

print(history.history.keys())发现有4个：
dict_keys(['val_loss', 'val_crf_viterbi_accuracy', 'loss', 'crf_viterbi_accuracy'])
把 'acc' 改成 'crf_viterbi_accuracy'

**Comment by wangjiaxu** [comment]
有知道为什么结果的loss很大，都是十几呢？正确率却挺高的。
 - loss: 17.5805 - crf_viterbi_accuracy: 0.9911 - val_loss: 15.6539 - val_crf_viterbi_accuracy: 0.8773
 - loss: 17.5799 - crf_viterbi_accuracy: 0.9915 - val_loss: 15.6227 - val_crf_viterbi_accuracy: 0.8833
 - loss: 17.5801 - crf_viterbi_accuracy: 0.9915 - val_loss: 15.6512 - val_crf_viterbi_accuracy: 0.8796
 - loss: 17.5808 - crf_viterbi_accuracy: 0.9909 - val_loss: 15.6785 - val_crf_viterbi_accuracy: 0.8777

**Comment by YowFung** [comment]
使用 python 3.7 版本，并且 `pip install tensorflow==1.14.0`、`pip install Keras==2.2.0` 和 `pip install git+https://www.github.com/keras-team/keras-contrib.git`。
